### ISSUE TITLE
Read all events for process instances starting before cutofftime (but ending after)

### ISSUE THREAD

**Issue by MagdalenaLang1** [viadee/camunda-kafka-polling-client#50]
When cutofftime falls between start and end of a process instance, some related events are potentially never read, leaving an inconsistency in the data. In particular, activity events of activities that ended before the cutofftime.

**Comment by MTwelkemeier** [comment]
The general idea of the cutoff timestamp, in contrast to the start timestamp, is to guarantee polling all events for an process instance or none at all: If a process instance starts before cutoff timestamp, no events for the process should be polled at all.

Thus, activities that ended before cutoff should not be polled, since the corresponding process started before cutoff timestamp. Neither the process instance itself nor the activities after the cutoff timestamp should be polled.

Can you provide some details regarding the timing of the process instance which is polled partially? (Cutoff time, polling start time, event timestamps)
